### ISSUE TITLE
Cannot build emfviews using Maven

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [atlanmod/emfviews#4] opened 2018-12-05 12:17 UTC
Bonjour,
I've followed the installation instructions to build EMFViews from Git sources, using Maven. However, the Maven build fails because of a missing dependency:
`[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.atlanmod.emfviews.tests 0.3.0.qualifier
[ERROR]   Missing requirement: org.atlanmod.emfviews.tests 0.3.0.qualifier requires 'bundle org.atlanmod.sexp2emf 0.1.0' but it could not be found
`
Bien cordialement
Yosu

**Comment by fmdkdd** [comment] 2018-12-05 14:55
Right, you need `sexp2emf` only to run the tests, but since we are pulling dependencies from the Eclipse manifests, you cannot skip it with `-DskipTests`.

I've added instructions to install [sexp2emf](https://github.com/atlanmod/sexp2emf) first.  Hopefully at some point we'll get it uploaded on maven central so you don't have this extra step.

**Comment by jesus-gorronogoitia** [comment] 2018-12-05 15:07
Thanks @fmdkdd I've installed `sexp2emf` , so building EMFViews with Maven now progresses, but at certain point it fails when building `org.atlanmod.emfviews.doc`  with the following error:
`[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:1.1.0:package-plugin (default-package-plugin) on project org.atlanmod.emfviews.doc: /home/yosu/Projects/MegaMart/Git/platform/emfviews/doc/org.atlanmod.emfviews.doc/build.properties: bin.includes value(s) [html/, toc.xml] do not match any files.`

**Comment by fmdkdd** [comment] 2018-12-05 15:25
Ah yes, you also need to generate the manual.  That is slightly more involved.  If you *really want to*, here is the one-line solution with Docker:

https://github.com/atlanmod/emfviews/blob/348588e8923d2b2194c9e6dc64a5d32d8e42a427/.travis.yml#L21-L24

But really, I would prefer a way to make that step optional.  Users don't need to build the manual usually.  I'll look into that.  Thanks for the reporting!

**Comment by jesus-gorronogoitia** [comment] 2018-12-05 15:36
So, I should skip that doc module, But if I try to skip it in Maven with:
`mvn install -DskipTests -pl '!doc'`
I still have the same error, the doc submodule is still built.
Do you remember how to skip it? Thanks

**Comment by fmdkdd** [comment] 2018-12-05 16:12
I think it's because the `features` submodule requires the doc plugin in any case.  I've added all of them to a separate profile in f126c5ca002d3f827271c527bc1ba19489b133ff, which is not activated by default.

After pulling this change, you should be able to build the plugins without the manual.

**Comment by jesus-gorronogoitia** [comment] 2018-12-05 16:57
Thanks, I could generate the doc following your readme. Now Maven building progresses, but fails in module
`org.atlanmod.emfviews.mel` with exception:
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (mwe2Launcher) on project org.atlanmod.emfviews.mel: Execution mwe2Launcher of goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:1.6.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:exec-maven-plugin:jar:1.6.0 -> org.eclipse.emf:org.eclipse.emf.mwe2.launch:jar:2.9.1.201705291010 -> org.eclipse.emf:org.eclipse.emf.mwe2.runtime:jar:[2.9.1.201705291010]: No versions available for org.eclipse.emf:org.eclipse.emf.mwe2.runtime:jar:[2.9.1.201705291010] within specified range -> [Help 1]`

**Comment by fmdkdd** [comment] 2018-12-05 17:53
That one is new.  I cannot reproduce, *but* I get a different error on my side from a fresh clone.  Our Travis builds have no issue building that, which is weird.

I'll investigate further.

**Comment by fmdkdd** [comment] 2018-12-06 16:24
Ok so I definitely cannot reproduce locally.  A Maven build from fresh clone works here.  The issue I was having was stemming from cloning into `/tmp`.  Anywhere else it works fine.

I've bumped the pom.xml dependencies in ac56779d2bafaae3be94ddef26c40a6ebf1747d2 to align with Eclipse 4.9, so you might have better luck with that one.

**Comment by jesus-gorronogoitia** [comment] 2018-12-10 13:21
Weird. I have a clean local clone of your repository, but still after a `mvn clean install` I am facing the same problem. I will try it from the update site.

**Comment by mosgilm** [comment] 2019-05-15 08:51
Bonjour,
              I was very interested to try the new concepts in emf views for myself.
I am able to use maven to build emfviews from the git repo successfully however I cannot use inside eclipse due to plugin dependency problems. 
I have installed all the required dependencies as the manual is quite good - however the one piece of info that would greatly help that I can't find is the eclipse version ?
I have also tried the update site however since its been a while since emfviews was created the latest eclipse (with correct dependencies) doesn't work anymore.

Thank you in advance,
                                   Maurice

**Comment by fmdkdd** [comment] 2019-05-17 13:25
> I can't find is the eclipse version ?

Anything from Oxygen and up should work.

>  its been a while since emfviews was created the latest eclipse (with correct dependencies) doesn't work anymore.

The update site works for me in a fresh Eclipse Modeling 2019-03.  You do need to install Epsilon first however.  Unfortunately, I didn't find any way to make Eclipse contact the Epsilon update site.  However, I've just split the plugin that depends on Epsilon in a different feature, since it's not essential.

**Comment by mosgilm** [comment] 2019-05-17 13:42
Thanks for your response.
I was able to get the EMFviews examples working by installing this version of eclipse :-

https://megamart2-ecsel.eu/megamrt2-eclipse-ide/

With additional plugins mentioned in the EMFview manual.
For epsilon I used 1.4 version from the update site:
http://download.eclipse.org/epsilon/1.4/updates/
As later epsilon versions (1.5 in this case) did not work for me.

**Comment by mosgilm** [comment] 2019-05-17 13:59
Thank you for splitting out epsilon into a separate feature.






From:
fmdkdd <notifications@github.com>
To:
atlanmod/emfviews <emfviews@noreply.github.com>, 
Cc:
mosgilm <m.gilmore@pilz.ie>, Comment <comment@noreply.github.com>
Date:
17/05/2019 14:25
Subject:
Re: [atlanmod/emfviews] Cannot build emfviews using Maven (#4)



I can't find is the eclipse version ?
Anything from Oxygen and up should work.
its been a while since emfviews was created the latest eclipse (with 
correct dependencies) doesn't work anymore.
The update site works for me in a fresh Eclipse Modeling 2019-03. You do 
need to install Epsilon first however. Unfortunately, I didn't find any 
way to make Eclipse contact the Epsilon update site. However, I've just 
split the plugin that depends on Epsilon in a different feature, since 
it's not essential.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.



This e-mail, including any attachments, may contain private or confidential information. Any unauthorised disclosure, copying or distribution of the confidential information contained therein, or the taking of any action based on it, is prohibited. The sender disclaims any liability for the integrity of this email. Legally binding declarations must be in written form.  If you think you may not be the intended recipient, or if you have received this e-mail in error, please contact the sender immediately and delete all copies of this e-mail.  If you are not the intended recipient, you must not reproduce any part of this e-mail or disclose its contents to any other party. This message represents the opinion of the sender and not necessarily the opinion of the company.

**Comment by fmdkdd** [comment] 2019-05-17 14:02
> As later epsilon versions (1.5 in this case) did not work for me.

That's curious.  I get no issue with 1.5.  But EMF Views should work fine with 1.4 anyway.

**Comment by jameswpm** [comment] 2023-03-05 13:27
The issue is outdated and has already been fixed within newer versions.

**Closed by jameswpm** 2023-03-05 13:27 UTC
